### ISSUE TITLE
Not working with <b> tag inside label

### ISSUE THREAD

**Issue by chiragdoshi90** [utatti/react-render-html#29]
`<input type="radio" id="myId" name="radio-group"/>`
`<label htmlFor="myId">`
        ` <label> {renderHTML('<p><b>Apple</b>')}</label>`
`</label>`
Result: 'Apple' without bold
But expected with bold characters

**Comment by utatti** [comment]
I've just tested the code out and it seems like working with no problem. What is your result HTML? Couldn't it be a style problem?

**Comment by chiragdoshi90** [comment]
The result is Apple without bold, whereas I have used 'b' tag inside renderHTML, I believe it should be **Apple**

**Comment by utatti** [comment]
I mean the actual HTML result in DOM. You can check it in devtools.
