### ISSUE TITLE
Upgrade to React 16.1

### ISSUE THREAD

**Issue by justinhp** [utatti/react-render-html#32]
Great library!  When you get a chance, can you please upgrade the React dependency to v16.1.

Thanks!
Justin

**Comment by utatti** [comment]
Sure. I'll do this today.

**Comment by utatti** [comment]
Actually, everything just works with v16.1.0 too. (There are some minor fixes in tests though)

Please use `react-render-html@0.6.0`. Thanks!

**Comment by justinhp** [comment]
Appreciate it!  Thanks for the quick reply!  Works great!
